# Generated by Django 5.0.7 on 2026-01-01 15:57

import django.core.validators
import store.models
import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_recipient_is_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to=store.models.order_receipt_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'pdf'], message='فرمت فایل مجاز نیست.'), store.validators.MaxFileSizeValidator(5242880, message='حجم فایل بیش از حد مجاز است.')]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(upload_to=store.models.product_image_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'], message='فرمت تصویر مجاز نیست.'), store.validators.MaxFileSizeValidator(8388608, message='حجم تصویر بیش از حد مجاز است.')]),
        ),
    ]
