# Generated by Django 5.0.7 on 2026-01-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_order_receipt_file_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Cart item', 'verbose_name_plural': 'Cart items'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='manualinvoicesequence',
            options={'verbose_name': 'Manual invoice sequence', 'verbose_name_plural': 'Manual invoice sequences'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order item', 'verbose_name_plural': 'Order items'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productfeature',
            options={'verbose_name': 'Product feature', 'verbose_name_plural': 'Product features'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_primary', 'sort_order', 'id'], 'verbose_name': 'Product image', 'verbose_name_plural': 'Product images'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product review', 'verbose_name_plural': 'Product reviews'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': 'Shipping address', 'verbose_name_plural': 'Shipping addresses'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='datasheet',
            field=models.FileField(blank=True, upload_to='products/datasheets/'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card_to_card', 'Card to card'), ('contact_admin', 'Contact admin')], max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='unpaid', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('unpaid', 'Unpaid'), ('paid', 'Paid'), ('sent', 'Sent'), ('done', 'Done'), ('canceled', 'Canceled')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated values', max_length=250, verbose_name='Tags'),
        ),
    ]
