# Generated by Django 5.0.7 on 2026-01-04 01:01

import django.core.validators
import django.db.models.deletion
import store.models
import store.validators
from django.utils.text import slugify
from django.db import migrations, models


def populate_category_slugs(apps, schema_editor):
    Category = apps.get_model("store", "Category")
    seen = set()
    for category in Category.objects.order_by("id"):
        base = slugify(category.name, allow_unicode=True) or f"category-{category.id}"
        slug = (category.slug or base).strip()
        if slug in seen:
            suffix = 1
            candidate = f"{base}-{suffix}"
            while candidate in seen:
                suffix += 1
                candidate = f"{base}-{suffix}"
            slug = candidate
        category.slug = slug
        category.save(update_fields=["slug"])
        seen.add(slug)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_cartitem_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='manualinvoicesequence',
            options={'verbose_name': 'سریال فاکتور دستی', 'verbose_name_plural': 'سریال فاکتور دستی'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productfeature',
            options={'verbose_name': 'مشخصه محصول', 'verbose_name_plural': 'مشخصات محصول'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_primary', 'sort_order', 'id'], 'verbose_name': 'تصویر محصول', 'verbose_name_plural': 'تصاویر محصول'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'نظر مشتری', 'verbose_name_plural': 'نظرات مشتریان'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales_count',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='email',
        ),
        migrations.AddField(
            model_name='productreview',
            name='role',
            field=models.CharField(blank=True, max_length=120, verbose_name='سمت / مجموعه'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام دسته'),
        ),
        migrations.RunPython(
            code=populate_category_slugs,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='manualinvoicesequence',
            name='last_number',
            field=models.PositiveIntegerField(default=0, verbose_name='آخرین شماره'),
        ),
        migrations.AlterField(
            model_name='manualinvoicesequence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datasheet',
            field=models.FileField(blank=True, upload_to='products/datasheets/', verbose_name='کاتالوگ/دیتاشیت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='domain',
            field=models.CharField(max_length=100, verbose_name='دامنه کاربرد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='موجود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, verbose_name='کد SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.CharField(blank=True, max_length=300, verbose_name='خلاصه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='برچسب\u200cها را با فاصله یا ویرگول جدا کنید.', max_length=250, verbose_name='برچسب\u200cها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='name',
            field=models.CharField(max_length=100, verbose_name='عنوان ویژگی'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='store.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='value',
            field=models.CharField(max_length=200, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(upload_to=store.models.product_image_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'], message='فرمت تصویر مجاز نیست.'), store.validators.MaxFileSizeValidator(8388608, message='حجم تصویر بیش از حد مجاز است.')], verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='comment',
            field=models.TextField(verbose_name='نظر'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='name',
            field=models.CharField(max_length=120, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
