# Generated by Django 5.0.7 on 2026-01-04 10:25

from django.db import migrations
from django.utils.text import slugify


def populate_product_slugs(apps, schema_editor):
    Product = apps.get_model("store", "Product")
    seen = {}
    for product in Product.objects.select_related("category").order_by("id"):
        category_id = product.category_id
        existing = seen.setdefault(category_id, set())
        base = slugify(product.name, allow_unicode=True) or f"product-{product.id}"
        slug = (product.slug or base).strip() or base
        if slug in existing:
            suffix = 1
            candidate = f"{base}-{suffix}"
            while candidate in existing:
                suffix += 1
                candidate = f"{base}-{suffix}"
            slug = candidate
        if product.slug != slug:
            product.slug = slug
            product.save(update_fields=["slug"])
        existing.add(slug)


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_remove_order_shipping_address_remove_order_user_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=populate_product_slugs,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
