# Generated by Django 5.2.8 on 2025-12-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_paymentsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatthread',
            name='user',
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=64, verbose_name='آیدی تلگرام (با @)'),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatThread',
        ),
    ]
