# Generated by Django 5.0.7 on 2025-12-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_paymentsettings_company_address_and_more'),
        ('store', '0012_order_recipient_is_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='eligible_products',
            field=models.ManyToManyField(blank=True, related_name='discount_codes', to='store.product', verbose_name='محصولات مشمول تخفیف'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='max_items_subtotal',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر جمع کالاها (تومان)'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='min_items_subtotal',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حداقل جمع کالاها (تومان)'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='شروع اعتبار'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='پایان اعتبار'),
        ),
    ]
