# Generated by Django 5.0.7 on 2026-01-03 20:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_discountcode_eligible_products_and_more'),
        ('store', '0014_alter_cartitem_options_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': '??????? ??????', 'verbose_name_plural': '??????????? ??????'},
        ),
        migrations.AlterModelOptions(
            name='discountcode',
            options={'verbose_name': '?? ?????', 'verbose_name_plural': '????? ?????'},
        ),
        migrations.AlterModelOptions(
            name='discountredemption',
            options={'ordering': ['-created_at'], 'verbose_name': '??????? ?? ?? ?????', 'verbose_name_plural': '??????????? ?? ?????'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': '?????', 'verbose_name_plural': '????????'},
        ),
        migrations.AlterModelOptions(
            name='paymentsettings',
            options={'verbose_name': '??????? ??????', 'verbose_name_plural': '??????? ??????'},
        ),
        migrations.AlterModelOptions(
            name='shippingsettings',
            options={'verbose_name': '??????? ??????', 'verbose_name_plural': '??????? ??????'},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='inquiry_type',
            field=models.CharField(choices=[('product', '??????? ?????'), ('service', '??????? ?????'), ('consultation', '??????? ??????'), ('other', '???? ?????')], default='consultation', max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='product_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='store.product'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='service_package',
            field=models.CharField(blank=True, choices=[('normal', '???? Normal'), ('vip', '???? VIP'), ('cip', '???? CIP')], max_length=20),
        ),
        migrations.AddField(
            model_name='news',
            name='cover_image',
            field=models.FileField(blank=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_discount_codes', to=settings.AUTH_USER_MODEL, verbose_name='????? ???????'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='?? ?????'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='eligible_products',
            field=models.ManyToManyField(blank=True, related_name='discount_codes', to='store.product', verbose_name='??????? ?????'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='????? ?????'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='max_items_subtotal',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='?????? ???? ??? (?????)'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='?????? ????? ???????'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='max_uses_per_user',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='?????? ????? ???? ?? ?????'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='min_items_subtotal',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='????? ???? ??? (?????)'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='percent',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='???? ?????'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='public_message',
            field=models.CharField(blank=True, max_length=200, verbose_name='??? ?????'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='source_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='?? ????'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='uses_count',
            field=models.PositiveIntegerField(default=0, verbose_name='????? ???????'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='???? ??????'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='????? ??????'),
        ),
        migrations.AlterField(
            model_name='discountredemption',
            name='discount_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='core.discountcode', verbose_name='?? ?????'),
        ),
        migrations.AlterField(
            model_name='discountredemption',
            name='order_id',
            field=models.PositiveIntegerField(verbose_name='????? ?????'),
        ),
        migrations.AlterField(
            model_name='discountredemption',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='?????'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='card_holder',
            field=models.CharField(blank=True, max_length=120, verbose_name='??? ???? ????'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='card_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='????? ????'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='company_address',
            field=models.TextField(blank=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='????? ????'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='company_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='???? ????'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='company_website',
            field=models.URLField(blank=True, verbose_name='??????'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=64, verbose_name='??????? ?????? (???? @)'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='????? ??????'),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='free_shipping_min_total',
            field=models.PositiveIntegerField(default=0, verbose_name='????? ???? ???? ????? ?????? (?????)'),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='shipping_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='????? ?????? (?????)'),
        ),
    ]
