# Generated by Django 5.0.7 on 2026-01-04 01:01

import django.db.models.deletion
import django.utils.timezone
from django.utils.text import slugify
from django.conf import settings
from django.db import migrations, models


def populate_news_slugs(apps, schema_editor):
    News = apps.get_model("core", "News")
    seen = set()
    for item in News.objects.order_by("id"):
        base = slugify(item.title, allow_unicode=True) or f"project-{item.id}"
        slug = (item.slug or base).strip()
        if slug in seen:
            suffix = 1
            candidate = f"{base}-{suffix}"
            while candidate in seen:
                suffix += 1
                candidate = f"{base}-{suffix}"
            slug = candidate
        item.slug = slug
        item.save(update_fields=["slug"])
        seen.add(slug)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_download'),
        ('store', '0015_remove_order_shipping_address_remove_order_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingSettings',
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'پیام تماس', 'verbose_name_plural': 'پیام\u200cهای تماس'},
        ),
        migrations.AlterModelOptions(
            name='dailyvisitstat',
            options={'verbose_name': 'آمار روزانه', 'verbose_name_plural': 'آمار روزانه'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'پروژه', 'verbose_name_plural': 'پروژه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='paymentsettings',
            options={'verbose_name': 'تنظیمات اطلاعات تماس', 'verbose_name_plural': 'تنظیمات اطلاعات تماس'},
        ),
        migrations.AlterModelOptions(
            name='sitevisit',
            options={'verbose_name': 'بازدید', 'verbose_name_plural': 'بازدیدها'},
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='card_holder',
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='card_number',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='company',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام مجموعه'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='inquiry_type',
            field=models.CharField(choices=[('product', 'استعلام محصول'), ('service', 'خدمات و پروژه'), ('consultation', 'مشاوره'), ('other', 'سایر')], default='consultation', max_length=20, verbose_name='نوع درخواست'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='product_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='store.product', verbose_name='محصول موردنظر'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پاسخ'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='service_package',
            field=models.CharField(blank=True, choices=[('normal', 'پکیج Normal'), ('vip', 'پکیج VIP'), ('cip', 'پکیج CIP')], max_length=20, verbose_name='پکیج'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'جدید'), ('replied', 'پاسخ داده شده')], default='new', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='dailyvisitstat',
            name='date',
            field=models.DateField(db_index=True, unique=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='dailyvisitstat',
            name='total_hits',
            field=models.PositiveIntegerField(default=0, verbose_name='کل بازدیدها'),
        ),
        migrations.AlterField(
            model_name='dailyvisitstat',
            name='unique_sessions',
            field=models.PositiveIntegerField(default=0, verbose_name='نشست\u200cهای یکتا'),
        ),
        migrations.AlterField(
            model_name='download',
            name='category',
            field=models.CharField(blank=True, max_length=120, verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='download',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='download',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='download',
            name='file',
            field=models.FileField(upload_to='downloads/', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='download',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='download',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='news',
            name='cover_image',
            field=models.FileField(blank=True, upload_to='projects/', verbose_name='تصویر شاخص'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.RunPython(
            code=populate_news_slugs,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.CharField(blank=True, max_length=300, verbose_name='خلاصه'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='company_address',
            field=models.TextField(blank=True, verbose_name='آدرس شرکت'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل شرکت'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='company_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='تلفن شرکت'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='company_website',
            field=models.URLField(blank=True, verbose_name='وب\u200cسایت'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=64, verbose_name='شناسه تلگرام'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره واتساپ'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='first_path',
            field=models.CharField(blank=True, max_length=200, verbose_name='اولین مسیر'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='session_key',
            field=models.CharField(db_index=True, max_length=40, verbose_name='شناسه نشست'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visits', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='visited_on',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='تاریخ بازدید'),
        ),
        migrations.DeleteModel(
            name='DiscountCode',
        ),
        migrations.DeleteModel(
            name='DiscountRedemption',
        ),
    ]
