# Generated by Django 5.0.7 on 2026-01-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_discountcode_assigned_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='service_package',
            field=models.CharField(blank=True, choices=[('normal', 'پکیج Basic'), ('vip', 'پکیج VIP'), ('cip', 'پکیج CIP')], max_length=20, verbose_name='پکیج'),
        ),
    ]
