# Generated by Django 5.0.7 on 2026-01-04 11:48

from django.db import migrations, models


def migrate_contact_packages(apps, schema_editor):
    ContactMessage = apps.get_model("core", "ContactMessage")
    ContactMessage.objects.filter(service_package="normal").update(service_package="basic")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_contactmessage_service_package"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="service_package",
            field=models.CharField(
                blank=True,
                choices=[("basic", "پکیج Basic"), ("vip", "پکیج VIP"), ("cip", "پکیج CIP")],
                max_length=20,
                verbose_name="پکیج",
            ),
        ),
        migrations.RunPython(migrate_contact_packages, reverse_code=migrations.RunPython.noop),
    ]
