# Generated by Django 5.2.8 on 2026-01-07 19:52

from django.db import migrations


def fix_orphaned_records(apps, schema_editor):
    """
    Data migration to fix orphaned records that might cause IntegrityErrors.
    This safely handles records that reference non-existent parent records.
    """
    db_alias = schema_editor.connection.alias
    
    # Get models
    ContactMessage = apps.get_model('core', 'ContactMessage')
    SiteVisit = apps.get_model('core', 'SiteVisit')
    Product = apps.get_model('store', 'Product')
    ProductImage = apps.get_model('store', 'ProductImage')
    ProductFeature = apps.get_model('store', 'ProductFeature')
    ProductReview = apps.get_model('store', 'ProductReview')
    
    # Fix ContactMessage.product_interest (SET_NULL is safe - just set to NULL)
    orphaned_contacts = ContactMessage.objects.using(db_alias).filter(
        product_interest__isnull=False
    )
    valid_product_ids = set(Product.objects.using(db_alias).values_list('id', flat=True))
    
    fixed_contacts = 0
    for contact in orphaned_contacts:
        if contact.product_interest_id and contact.product_interest_id not in valid_product_ids:
            contact.product_interest_id = None
            contact.save(update_fields=['product_interest_id'])
            fixed_contacts += 1
    
    if fixed_contacts > 0:
        print(f'Fixed {fixed_contacts} ContactMessage records with orphaned product_interest')
    
    # Fix SiteVisit.user (SET_NULL is safe - just set to NULL)
    # Note: We can't easily check User model here, so we'll skip this
    # The SET_NULL on_delete should handle this automatically
    
    # Fix ProductImage, ProductFeature, ProductReview (CASCADE - should delete)
    # These should be automatically handled by CASCADE, but we'll clean up any orphans
    valid_product_ids = set(Product.objects.using(db_alias).values_list('id', flat=True))
    
    # Delete orphaned ProductImages
    orphaned_images = ProductImage.objects.using(db_alias).exclude(
        product_id__in=valid_product_ids
    )
    deleted_images = orphaned_images.count()
    orphaned_images.delete()
    if deleted_images > 0:
        print(f'Deleted {deleted_images} ProductImage records with orphaned product')
    
    # Delete orphaned ProductFeatures
    orphaned_features = ProductFeature.objects.using(db_alias).exclude(
        product_id__in=valid_product_ids
    )
    deleted_features = orphaned_features.count()
    orphaned_features.delete()
    if deleted_features > 0:
        print(f'Deleted {deleted_features} ProductFeature records with orphaned product')
    
    # Delete orphaned ProductReviews
    orphaned_reviews = ProductReview.objects.using(db_alias).exclude(
        product_id__in=valid_product_ids
    )
    deleted_reviews = orphaned_reviews.count()
    orphaned_reviews.delete()
    if deleted_reviews > 0:
        print(f'Deleted {deleted_reviews} ProductReview records with orphaned product')


def reverse_fix(apps, schema_editor):
    """Reverse migration - nothing to do as we can't restore deleted records"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_contactmessage_service_package'),
        ('store', '0016_populate_product_slugs'),  # Ensure store migrations are applied
    ]

    operations = [
        migrations.RunPython(fix_orphaned_records, reverse_fix),
    ]
