# Generated by Django 5.0.7 on 2025-12-22 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_privacy_and_marketing'),
        ('accounts', '0003_delete_phoneotp'),
    ]

    operations = [
    ]
