# Generated by Django 5.2.8 on 2025-12-19 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthIPBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('blocked_at', models.DateTimeField()),
                ('blocked_until', models.DateTimeField()),
                ('unblocked_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(default='too_many_failures', max_length=64)),
                ('last_user_identifier', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthIPEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('block', 'Block'), ('unblock', 'Unblock')], db_index=True, max_length=16)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reason', models.CharField(blank=True, max_length=64)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('user_identifier', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address', 'created_at'], name='auth_securi_ip_addr_654fb5_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuthIPBlockEvent',
            fields=[
            ],
            options={
                'verbose_name': 'IP Block Event',
                'verbose_name_plural': 'IP Block Events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth_security.authipevent',),
        ),
        migrations.CreateModel(
            name='AuthIPUnblockEvent',
            fields=[
            ],
            options={
                'verbose_name': 'IP Unblock Event',
                'verbose_name_plural': 'IP Unblock Events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth_security.authipevent',),
        ),
        migrations.CreateModel(
            name='AuthLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_identifier', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('succeeded', models.BooleanField(default=False)),
                ('reason', models.CharField(choices=[('invalid_credentials', 'Invalid credentials'), ('rate_limited_ip', 'Rate limited (IP)'), ('rate_limited_identifier', 'Rate limited (identifier)'), ('blocked_ip', 'Blocked IP'), ('missing_identifier', 'Missing identifier')], db_index=True, max_length=64)),
                ('path', models.CharField(blank=True, max_length=256)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address', 'created_at'], name='auth_securi_ip_addr_d0beee_idx'), models.Index(fields=['user_identifier', 'created_at'], name='auth_securi_user_id_526eaa_idx')],
            },
        ),
    ]
